name: Update Github Commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update GitHub Profile Page
    steps:
      - uses: actions/checkout@v2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-username: "WeiYun0912"
          user-email: "yher25@gmail.com"
